### ISSUE TITLE
Missing dependency: pygraphviz

### ISSUE THREAD

**Issue by acrosman** [SFDO-Tooling/Snowfakery#177]
On a Mac (10.15.6) using a a homebrew installed version of Python 3.8 and pipx installed version of Snowfakery when requesting an output file type of SVG or PNG (expect all image types) I get: `ModuleNotFoundError: No module named 'pygraphviz'`

$ snowfakery --version
snowfakery, version 1.2

$ python3 --version
Python 3.8.6

```
$ snowfakery --output-format=SVG --output-file gifts.svg snowfakery_npsp_basic_recipe.yml
Traceback (most recent call last):
  File "/Users/acrosman/.local/bin/snowfakery", line 8, in <module>
    sys.exit(main())
  File "/Users/acrosman/.local/pipx/venvs/snowfakery/lib/python3.8/site-packages/snowfakery/cli.py", line 271, in main
    generate_cli.main(prog_name="snowfakery")
  File "/Users/acrosman/.local/pipx/venvs/snowfakery/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/acrosman/.local/pipx/venvs/snowfakery/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/acrosman/.local/pipx/venvs/snowfakery/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/acrosman/.local/pipx/venvs/snowfakery/lib/python3.8/site-packages/snowfakery/cli.py", line 150, in generate_cli
    with configure_output_stream(
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/acrosman/.local/pipx/venvs/snowfakery/lib/python3.8/site-packages/snowfakery/cli.py", line 216, in configure_output_stream
    output_streams.append(ImageOutputStream(path, format))
  File "/Users/acrosman/.local/pipx/venvs/snowfakery/lib/python3.8/site-packages/snowfakery/output_streams.py", line 387, in __init__
    super().__init__(path)
  File "/Users/acrosman/.local/pipx/venvs/snowfakery/lib/python3.8/site-packages/snowfakery/output_streams.py", line 332, in __init__
    import pygraphviz
ModuleNotFoundError: No module named 'pygraphviz'
```

**Comment by prescod** [comment]
This will be fixed here:

https://github.com/SFDO-Tooling/Snowfakery/pull/171
