### ISSUE TITLE
Using with cumulusci: SqlOutputStream has no attribute from_connection

### ISSUE THREAD

**Issue by adamlincoln** [SFDO-Tooling/Snowfakery#29]
I am following the instructions here: https://salesforce.quip.com/AXY5A4WGTbNP#PJUACAQ5tGE

After verifying that it is properly configured (that is, `cci task info generate_and_load_from_yaml` does not throw an exception, I assume that means I've configured it correctly), I run

```
cci task run generate_and_load_from_yaml -o generator_yaml test.yml --org my-org
```

and I get

```
2020-04-16 10:27:13: No database URL: creating sqlite file generated_data.db
2020-04-16 10:27:13: Beginning task: GenerateDataFromYaml
2020-04-16 10:27:13:
2020-04-16 10:27:13: Generating batch 0 with 1

Error: type object 'SqlOutputStream' has no attribute 'from_connection'
Type `cci error --help` for more information about debugging errors.
```

Running `cci error --help` shows this traceback:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/cumulusci/3.10.0/libexec/lib/python3.7/site-packages/cumulusci/cli/cci.py", line 219, in main
    cli(standalone_mode=False)
  File "/usr/local/Cellar/cumulusci/3.10.0/libexec/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/cumulusci/3.10.0/libexec/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/cumulusci/3.10.0/libexec/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/cumulusci/3.10.0/libexec/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/cumulusci/3.10.0/libexec/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/cumulusci/3.10.0/libexec/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/cumulusci/3.10.0/libexec/lib/python3.7/site-packages/cumulusci/cli/cci.py", line 166, in new_func
    func(RUNTIME, *args, **kw)
  File "/usr/local/Cellar/cumulusci/3.10.0/libexec/lib/python3.7/site-packages/cumulusci/cli/cci.py", line 1307, in task_run
    task()
  File "/usr/local/Cellar/cumulusci/3.10.0/libexec/lib/python3.7/site-packages/cumulusci/core/tasks.py", line 138, in __call__
    self.result = self._run_task()
  File "/usr/local/Cellar/cumulusci/3.10.0/libexec/lib/python3.7/site-packages/cumulusci/tasks/bulkdata/base_generate_data_task.py", line 56, in _run_task
    self.current_batch_num,
  File "/usr/local/Cellar/cumulusci/3.10.0/libexec/lib/python3.7/site-packages/cumulusci/tasks/bulkdata/generate_from_yaml.py", line 92, in _generate_data
    self.generate_data(session, engine, base, num_records, current_batch_num)
  File "/usr/local/Cellar/cumulusci/3.10.0/libexec/lib/python3.7/site-packages/cumulusci/tasks/bulkdata/generate_from_yaml.py", line 141, in generate_data
    output_stream = SqlOutputStream.from_connection(
AttributeError: type object 'SqlOutputStream' has no attribute 'from_connection'
```

I see that Snowfakery doesn't implement the `from_connection` method in output_streams:SqlOutputStream.

It appears that I cannot use snowfakery with cci to push generated data to my org.

Please let me know if I can help more!  I'm happy to open a PR as long as I know the right answer is to add an implementation for `from_connection`.

**Comment by davisagli** [comment]
@prescod removed from_connection from snowfakery master but hasn't updated cumulusci to stop calling it yet. Paul, this is an example of why I was wary about telling people to install snowfakery from master instead of from a release.

**Comment by adamlincoln** [comment]
I see 0.6.3 on pypi - should I grab that or wait until another release?

**Comment by davisagli** [comment]
@adamlincoln very soon we'll be making a cumulusci release that comes with snowfakery included, so I would just wait for that if you're not in a hurry.
