### ISSUE TITLE
Getting Snowfakery work with MySQL

### ISSUE THREAD

**Issue by andygrunwald** [SFDO-Tooling/Snowfakery#801]
## Context

In [Using Snowfakery with Databases](https://snowfakery.readthedocs.io/en/docs/#using-snowfakery-with-databases) it is described how to use Snowfakery with PostgreSQL via `--dburl='postgresql://localhost:5432/snowfakerydb'`.

[SQLAlchemy also works with MySQL](https://docs.sqlalchemy.org/en/20/dialects/mysql.html).

Hence, I tried `snowfakery dummy_data.yml --dburl='mysql://...` and got

```sh
Traceback (most recent call last):
  File "/Users/my.user/.local/bin/snowfakery", line 8, in <module>
    sys.exit(main())
  File "/Users/my.user/.local/pipx/venvs/snowfakery/lib/python3.10/site-packages/snowfakery/cli.py", line 296, in main
    generate_cli.main(prog_name="snowfakery")
  File "/Users/my.user/.local/pipx/venvs/snowfakery/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/my.user/.local/pipx/venvs/snowfakery/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/my.user/.local/pipx/venvs/snowfakery/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/my.user/.local/pipx/venvs/snowfakery/lib/python3.10/site-packages/snowfakery/cli.py", line 230, in generate_cli
    generate_data(
  File "/Users/my.user/.local/pipx/venvs/snowfakery/lib/python3.10/site-packages/snowfakery/api.py", line 170, in generate_data
    output_stream = exit_stack.enter_context(
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 492, in enter_context
    result = _cm_type.__enter__(cm)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/my.user/.local/pipx/venvs/snowfakery/lib/python3.10/site-packages/snowfakery/api.py", line 215, in configure_output_stream
    with _get_output_streams(
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/my.user/.local/pipx/venvs/snowfakery/lib/python3.10/site-packages/snowfakery/api.py", line 244, in _get_output_streams
    output_streams.append(SqlDbOutputStream.from_url(dburl))
  File "/Users/my.user/.local/pipx/venvs/snowfakery/lib/python3.10/site-packages/snowfakery/output_streams.py", line 304, in from_url
    engine = create_engine(db_url)
  File "<string>", line 2, in create_engine
  File "/Users/my.user/.local/pipx/venvs/snowfakery/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/Users/my.user/.local/pipx/venvs/snowfakery/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/Users/my.user/.local/pipx/venvs/snowfakery/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 163, in dbapi
    return __import__("MySQLdb")
ModuleNotFoundError: No module named 'MySQLdb'
make: *** [data-sql] Error 1
```

## SQL Output

The SQL Output itself does not work with MySQL:

```
$ snowfakery dummy_data.yml --output-format sql --output-file mysql-init-data/dummy-data.sql
```

This creates content like

```sql
BEGIN TRANSACTION;
CREATE TABLE ...
````

[MySQL Transactions](https://dev.mysql.com/doc/refman/8.0/en/commit.html) start with `START TRANSACTION...`.

## Expected usecase

This works also with MySQL

## Open Questions

Can this work either to insert into MySQL directly OR to generate MySQL-compatible output?

## Version

Snowfakery was installed via `pipx install snowfakery` in version 

```sh
$ snowfakery --version
snowfakery version 3.4.0
You have the latest version of Snowfakery

Program: /Users/my.user/.local/pipx/venvs/snowfakery/lib/python3.10/site-packages/snowfakery/cli.py
Python: 3.10.9 (main, Dec 15 2022, 10:44:50) [Clang 14.0.0 (clang-1400.0.29.202)]
Executable: /Users/my.user/.local/pipx/venvs/snowfakery/bin/python
Installation: Properly installed
```

**Comment by andygrunwald** [comment]
For the SQL output a small workaround helps:

```sh
$ snowfakery dummy_data.yml --output-format sql --output-file ./mysql-init-data/01-dummy_data.sql
sed -i '' 's/BEGIN TRANSACTION/START TRANSACTION/g' ./mysql-init-data/01-dummy_data.sql
sed -i '' -E 's/INSERT INTO "([a-zA-Z_-]*)" VALUES/INSERT INTO `\1` VALUES/g' ./mysql-init-data/01-dummy_data.sql
```

**Comment by prescod** [comment]
Sorry for the delay @andygrunwald . The docs say: "You should start by installing Snowfakery in a context which makes it easy to use the Python command 'pip' to manage your Python environment. For example you could install Python using the standard installers from python.org and then you would run the following commands to create and use a venv with the Postgres package:"

In this case you need to PIP install a MySQL driver instead of a Postgres driver. We can't really "fix" this without bloating Snowfakery with extra drivers, but we could improve the error message and perhaps give pointers to how to install drivers.


```
pip install mysql-connector-python
```

Then your URL should start with `mysql+mysqlconnector://`

@jkasturi-sf the messaging is easy to fix.

**Comment by andygrunwald** [comment]
Thanks @prescod.
I will give it a try.

The doc is one thing. The SQL dialect another. PG SQL != MySQL dialect (see `BEGIN` vs. `START` Transaction above).

**Comment by prescod** [comment]
@andygrunwald : If you connect directly to the database as described above then I don't think that the syntax will be a problem. 

Docs were updated to clarify how to install the `driver`.
