### ISSUE TITLE
Windows 237 NotADirectory Error with Salesforce Query

### ISSUE THREAD

**Issue by allisonletts** [SFDO-Tooling/Snowfakery#901]
I'm running Windows with VSCode-based Powershell and snowfakery 3.5.
When I try to run a [snowfakery recipe](https://github.com/SFDO-Community-Sprints/Snowfakery-Recipe-Templates/blob/main/snowfakery_samples/OSC/MembershipSchemaAndBenefits_PricebookProducts.recipe.yml) that queries Salesforce records, I receive an error message.

This appears to be the crux of the issue: 
`NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\ALLISO~1\\AppData\\Local\\Temp\\tmp9b9uku52\\queryresults.db'`

Full documentation:
https://gist.github.com/allisonletts/994828955eb9c266936f73b4d9e52b4b

**Comment by allisonletts** [comment]
I'm still having the same issue: https://gist.github.com/allisonletts/0e575f28e49834d676c0571dcd3b88c0

**Comment by acrosman** [comment]
This continues to be an issue on Windows 11.

**Comment by allisonletts** [comment]
@acrosman have you attempted on a mac? I haven't, but could.

**Comment by acrosman** [comment]
When I ran into it the other day I'm reasonably confident it stopped cold.  I ended up re-writing the recipe to avoid the `- plugin: snowfakery.standard_plugins.Salesforce.SOQLDataset` entirely, so it'll need to try to assembly a minimal example when I have a few minutes.

**Comment by allisonletts** [comment]
Yeah, I also had it stop, I'm pretty sure.

**Comment by acrosman** [comment]
Using this as a proposed testing recipe (posted as a way to get from one machine to another).  This works on a Mac with snowfakery 3.6.2

```yml
- plugin: snowfakery.standard_plugins.Salesforce.SalesforceQuery

- object: Contact
  fields:
    LastName:
      fake: LastName
    AccountId:
      SalesforceQuery.random_record:
        from: Account
```

**Comment by acrosman** [comment]
I found a minimal recipe to create a blocking error, but the conditions are a little more complicated than I expected. Smallest recipe I've found so far is one that involves multiple objects and multiple queries.  Having two queries will generate the error message, but the recipe will run successfully. Having queries across multiple objects appears to be the key.

```yml
- plugin: snowfakery.standard_plugins.Salesforce.SOQLDataset
- object: Contact
  count: 10
  fields:
    __users_from_salesforce:
      SOQLDataset.shuffle:
        fields: Id, FirstName, LastName
        from: User
    # The next line depends on the users having particular
    # permissions.
    OwnerId: ${{__users_from_salesforce.Id}}
    FirstName: ${{__users_from_salesforce.FirstName}}
    LastName: ${{__users_from_salesforce.LastName}}

- object: PricebookEntry
  fields:
    IsActive: true
    UnitPrice: 250
    __product_from_salesforce:
      SOQLDataset.shuffle:
        fields: Id
        from: Product2
    Product2Id: ${{__product_from_salesforce.Id}}
    __pricebook_from_salesforce:
      SOQLDataset.shuffle:
        fields: Id
        from: Pricebook2
    Pricebook2Id: ${{__pricebook_from_salesforce.Id}}
```

Yes, this one is somewhat gibberish, but it _should_ be valid.

If you run just the Contact section (which queries users) or just the Pricebook entry it work. But if you run both sections it fails to load the PBE.

```
> cci task run generate_and_load_from_yaml --generator_yaml test.recipe.yml --org otter
[04/02/24 21:13:02] Org info updated, writing to keychain
                    Beginning task: GenerateAndLoadDataFromYaml
                    As user: ahcrosman@playful-otter-bkoezw.com
                    In org: 00D4x000006sV5eEAE

                    Beginning task: GenerateDataFromYaml

Exception ignored in: <finalize object at 0x2246d49cf40; dead>
Traceback (most recent call last):
  File "C:\Python311\Lib\weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\tempfile.py", line 894, in _cleanup
    cls._rmtree(name, ignore_errors=ignore_errors)
  File "C:\Python311\Lib\tempfile.py", line 890, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Python311\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Python311\Lib\tempfile.py", line 881, in onerror
    cls._rmtree(path, ignore_errors=ignore_errors)
  File "C:\Python311\Lib\tempfile.py", line 890, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Python311\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\shutil.py", line 603, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Python311\Lib\shutil.py", line 600, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
         ^^^^^^^^^^^^^^^^
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\acros\\AppData\\Local\\Temp\\tmpn9yyugq_\\queryresults.db'
Exception ignored in: <finalize object at 0x2246d49d120; dead>
Traceback (most recent call last):
  File "C:\Python311\Lib\weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\tempfile.py", line 894, in _cleanup
    cls._rmtree(name, ignore_errors=ignore_errors)
  File "C:\Python311\Lib\tempfile.py", line 890, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Python311\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Python311\Lib\tempfile.py", line 881, in onerror
    cls._rmtree(path, ignore_errors=ignore_errors)
  File "C:\Python311\Lib\tempfile.py", line 890, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Python311\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\shutil.py", line 603, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Python311\Lib\shutil.py", line 600, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
         ^^^^^^^^^^^^^^^^
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\acros\\AppData\\Local\\Temp\\tmpmw7pj3l_\\queryresults.db'
[04/02/24 21:13:04] Generated batch
                    Org info updated, writing to keychain
                    Beginning task: LoadData
                    As user: ahcrosman@playful-otter-bkoezw.com
                    In org: 00D4x000006sV5eEAE

[04/02/24 21:13:06] Running step: Insert Contact
                    Creating insert Operation for Contact using smart
                    Prepared 10 rows for insert to Contact.

Error: Error on record with id 3: OP_WITH_INVALID_USER_TYPE_EXCEPTION: Operation not valid for this user type ()
Run this command for more information about debugging errors: cci error --help
```

I tested the recipe against a Trailhead org so the queried data will exist.

**Comment by acrosman** [comment]
I've been experimenting with recipes tonight trying to find one that actually blocks the run, and reproduces the errors.

What I've managed to do so far is get recipes that will produce the error, but support @prescod's assertion that it does not block completion.  It also seems to only occur in recipes that have multiple queries.  Any other error in the recipe will block completion of the inserts, but the ones I created were all unrelated (a few looked like they were).

The error only appears on Windows, not Mac. Requires two or more queries. The error message does not appear to block completion (that I can find so far).

```yml
- plugin: snowfakery.standard_plugins.Salesforce.SOQLDataset
- object: Contact
  count: 10
  fields:
    __users_from_salesforce:
      SOQLDataset.shuffle:
        fields: Id, FirstName, LastName
        from: User
    __Account_from_Salesforce:
      SOQLDataset.shuffle:
        fields: Id
        from: Account
    # The next line depends on the users having particular
    # permissions.
    FirstName: ${{__users_from_salesforce.FirstName}}
    LastName: ${{__users_from_salesforce.LastName}}
    AccountId: ${{__Account_from_Salesforce.Id}}
```
